.ONESHELL:

init:
	touch dev.env
	echo "DEBUG=True" > dev.env
	echo "MONGODB_HOST=test_mongodb" >> dev.env
	echo "MONGODB_PORT=27017" >> dev.env
	echo "MONGODB_USERNAME=test" >> dev.env
	echo "MONGODB_PASSWORD=test" >> dev.env
	docker network create test